import {defineConfig} from 'oxlint';

export default defineConfig({
    categories: {
        correctness: 'error',
    },
    env: {
        browser: true,
        node: true,
        serviceworker: true,
    },
    ignorePatterns: ['**/*.d.ts', '**/*.d.mts', '**/build/**', '**/dist/**', '**/sanity.types.ts'],
    options: {
        typeAware: true,
    },
    overrides: [
        {
            files: ['**/*.{js,jsx,mjs,cjs}'],
            plugins: ['oxc', 'unicorn'],
            rules: {
                'typescript/ban-ts-comment': 'off',
                'typescript/no-empty-object-type': 'off',
                'typescript/no-explicit-any': 'off',
                'typescript/no-misused-promises': 'off',
                'typescript/no-namespace': 'off',
                'typescript/no-require-imports': 'off',
                'typescript/no-unnecessary-type-assertion': 'off',
                'typescript/no-unnecessary-type-constraint': 'off',
                'typescript/no-unsafe-argument': 'off',
                'typescript/no-unsafe-assignment': 'off',
                'typescript/no-unsafe-call': 'off',
                'typescript/no-unsafe-enum-comparison': 'off',
                'typescript/no-unsafe-function-type': 'off',
                'typescript/no-unsafe-member-access': 'off',
                'typescript/no-unsafe-return': 'off',
                'typescript/only-throw-error': 'off',
                'typescript/prefer-promise-reject-errors': 'off',
                'typescript/require-await': 'off',
                'typescript/restrict-plus-operands': 'off',
            },
        },
    ],
    plugins: ['oxc', 'typescript', 'unicorn'],
    rules: {
        'eslint/no-array-constructor': 'error',
        'eslint/no-case-declarations': 'error',
        'eslint/no-empty': 'error',
        'eslint/no-fallthrough': 'error',
        'eslint/no-prototype-builtins': 'error',
        'eslint/no-regex-spaces': 'error',
        'eslint/no-unexpected-multiline': 'error',
        'eslint/no-useless-assignment': 'error',
        'eslint/no-var': 'error',
        'eslint/prefer-const': 'error',
        'eslint/prefer-rest-params': 'error',
        'eslint/prefer-spread': 'error',
        'eslint/preserve-caught-error': 'error',
        'typescript/ban-ts-comment': 'error',
        'typescript/no-empty-object-type': 'error',
        'typescript/no-explicit-any': 'warn',
        'typescript/no-misused-promises': [
            'error',
            {
                checksVoidReturn: false,
            },
        ],
        'typescript/no-namespace': 'error',
        'typescript/no-require-imports': 'error',
        'typescript/no-unnecessary-type-assertion': 'error',
        'typescript/no-unnecessary-type-constraint': 'error',
        'typescript/no-unsafe-argument': 'error',
        'typescript/no-unsafe-assignment': 'error',
        'typescript/no-unsafe-call': 'error',
        'typescript/no-unsafe-enum-comparison': 'error',
        'typescript/no-unsafe-function-type': 'error',
        'typescript/no-unsafe-member-access': 'error',
        'typescript/no-unsafe-return': 'error',
        'typescript/only-throw-error': 'error',
        'typescript/prefer-promise-reject-errors': 'error',
        'typescript/require-await': 'error',
        'typescript/restrict-plus-operands': 'error',
    },
});
