import {defineConfig} from 'vite-plus';
import type {OxfmtConfig} from 'vite-plus/fmt';
import type {OxlintConfig} from 'vite-plus/lint';

const lintConfig: OxlintConfig = {
    plugins: ['typescript'],
    categories: {
        correctness: 'off',
    },
    env: {
        builtin: true,
        browser: true,
        es2024: true,
    },
    ignorePatterns: [
        '**/build/**',
        '**/dist/**',
        '**/scripts/compile-migrations.mjs',
        '**/scripts/migrate-json-to-blocks.ts',
        '**/scripts/validate-json-to-blocks.ts',
        '**/src/migrations.compiled.ts',
    ],
    rules: {
        'constructor-super': 'error',
        'for-direction': 'error',
        'getter-return': 'error',
        'no-async-promise-executor': 'error',
        'no-case-declarations': 'error',
        'no-class-assign': 'error',
        'no-compare-neg-zero': 'error',
        'no-cond-assign': 'error',
        'no-const-assign': 'error',
        'no-constant-binary-expression': 'error',
        'no-constant-condition': 'error',
        'no-control-regex': 'error',
        'no-debugger': 'error',
        'no-delete-var': 'error',
        'no-dupe-class-members': 'error',
        'no-dupe-else-if': 'error',
        'no-dupe-keys': 'error',
        'no-duplicate-case': 'error',
        'no-empty': 'error',
        'no-empty-character-class': 'error',
        'no-empty-pattern': 'error',
        'no-empty-static-block': 'error',
        'no-ex-assign': 'error',
        'no-extra-boolean-cast': 'error',
        'no-fallthrough': 'error',
        'no-func-assign': 'error',
        'no-global-assign': 'error',
        'no-import-assign': 'error',
        'no-invalid-regexp': 'error',
        'no-irregular-whitespace': 'error',
        'no-loss-of-precision': 'error',
        'no-misleading-character-class': 'error',
        'no-new-native-nonconstructor': 'error',
        'no-nonoctal-decimal-escape': 'error',
        'no-obj-calls': 'error',
        'no-prototype-builtins': 'error',
        'no-redeclare': 'error',
        'no-regex-spaces': 'error',
        'no-self-assign': 'error',
        'no-setter-return': 'error',
        'no-shadow-restricted-names': 'error',
        'no-sparse-arrays': 'error',
        'no-this-before-super': 'error',
        'no-unexpected-multiline': 'error',
        'no-unreachable': 'error',
        'no-unsafe-finally': 'error',
        'no-unsafe-negation': 'error',
        'no-unsafe-optional-chaining': 'error',
        'no-unused-labels': 'error',
        'no-unused-private-class-members': 'error',
        'no-unused-vars': 'error',
        'no-useless-backreference': 'error',
        'no-useless-catch': 'error',
        'no-useless-escape': 'error',
        'no-with': 'error',
        'require-yield': 'error',
        'use-isnan': 'error',
        'valid-typeof': 'error',
        'no-array-constructor': 'error',
        'typescript/ban-ts-comment': 'error',
        'typescript/ban-types': 'error',
        'typescript/no-duplicate-enum-values': 'error',
        'typescript/no-explicit-any': 'error',
        'typescript/no-extra-non-null-assertion': 'error',
        'typescript/no-misused-new': 'error',
        'typescript/no-namespace': 'error',
        'typescript/no-non-null-asserted-optional-chain': 'error',
        'typescript/no-this-alias': 'error',
        'typescript/no-unnecessary-type-constraint': 'error',
        'typescript/no-unsafe-declaration-merging': 'error',
        'typescript/no-var-requires': 'error',
        'typescript/prefer-as-const': 'error',
        'typescript/triple-slash-reference': 'error',
        '@stylistic/padding-line-between-statements': [
            'error',
            {blankLine: 'always', prev: '*', next: 'return'},
            {blankLine: 'always', prev: ['const', 'let'], next: '*'},
            {blankLine: 'always', prev: '*', next: ['const', 'let']},
            {blankLine: 'any', prev: ['const', 'let'], next: ['const', 'let']},
            {blankLine: 'always', prev: ['if', 'for', 'while', 'switch', 'class'], next: '*'},
            {blankLine: 'always', prev: 'directive', next: '*'},
            {blankLine: 'any', prev: 'directive', next: 'directive'},
        ],
    },
    overrides: [
        {
            files: ['**/*.ts', '**/*.tsx', '**/*.mts', '**/*.cts'],
            rules: {
                'constructor-super': 'off',
                'getter-return': 'off',
                'no-const-assign': 'off',
                'no-dupe-class-members': 'off',
                'no-dupe-keys': 'off',
                'no-func-assign': 'off',
                'no-import-assign': 'off',
                'no-new-native-nonconstructor': 'off',
                'no-obj-calls': 'off',
                'no-redeclare': 'off',
                'no-setter-return': 'off',
                'no-this-before-super': 'off',
                'no-unreachable': 'off',
                'no-unsafe-negation': 'off',
                'no-var': 'error',
                'prefer-const': 'error',
                'prefer-rest-params': 'error',
                'prefer-spread': 'error',
            },
        },
        {
            files: ['**/*.ts', '**/*.tsx'],
            rules: {
                'typescript/no-explicit-any': 'warn',
            },
        },
        {
            files: ['**/*.{jsx,tsx}'],
            rules: {
                'react/display-name': 'error',
                'react/jsx-key': 'error',
                'react/jsx-no-comment-textnodes': 'error',
                'react/jsx-no-duplicate-props': 'error',
                'react/jsx-no-target-blank': 'warn',
                'react/jsx-no-undef': 'error',
                'react/no-children-prop': 'error',
                'react/no-danger-with-children': 'error',
                'react/no-direct-mutation-state': 'error',
                'react/no-find-dom-node': 'error',
                'react/no-is-mounted': 'error',
                'react/no-render-return-value': 'error',
                'react/no-string-refs': 'error',
                'react/no-unescaped-entities': 'error',
                'react/no-unknown-property': 'error',
                'react/no-unsafe': 'off',
                'react/react-in-jsx-scope': 'off',
            },
        },
        {
            files: ['apps/**/*.{ts,tsx,js,jsx}', 'packages/**/*.{ts,tsx,js,jsx}'],
            rules: {
                curly: ['error', 'all'],
                'func-style': ['error', 'expression', {allowArrowFunctions: true}],
                'no-else-return': ['error', {allowElseIf: false}],
                'no-negated-condition': 'error',
                'no-nested-ternary': 'error',
                'prefer-arrow-callback': ['error', {allowNamedFunctions: false}],
            },
        },
    ],
    options: {
        typeAware: true,
        typeCheck: true,
    },
};

const fmtConfig: OxfmtConfig = {
    printWidth: 100,
    tabWidth: 4,
    useTabs: false,
    semi: true,
    singleQuote: true,
    trailingComma: 'all',
    bracketSpacing: false,
    arrowParens: 'avoid',
    endOfLine: 'lf',
    quoteProps: 'as-needed',
    sortImports: {
        internalPattern: ['@patekphillipe/*'],
    },
};

export default defineConfig({
    lint: lintConfig,
    fmt: fmtConfig,
    test: {
        include: ['**/*.test.{ts,tsx}', '**/*.spec.{ts,tsx}'],
    },
});
