import {
    useCallback,
    useMemo,
} from 'react';

import {useScriptEditorCharacters} from './editor/characters/useScriptEditorCharacters';
import type {UseScriptEditorCharactersArgs} from './editor/characters/useScriptEditorCharacters.types';
import type {ScriptCharactersContextValue} from './ScriptCharactersContext';

interface UseScriptCharactersContextValueResult {
    applyDocumentChange: ReturnType<typeof useScriptEditorCharacters>['applyDocumentChange'],
    getEditorValue: ReturnType<typeof useScriptEditorCharacters>['getEditorValue'],
    editorOverrideValue: ScriptCharactersContextValue['editorOverrideValue'],
    normalizedConfirmedCharacterRecords: ScriptCharactersContextValue['normalizedConfirmedCharacterRecords'],
    normalizedSpeakingEntityRecords: ScriptCharactersContextValue['normalizedSpeakingEntityRecords'],
    handleResolvedEditorValueChange: ScriptCharactersContextValue['handleEditorValueChange'],
    contextValue: ScriptCharactersContextValue,
}

export const useScriptCharactersContextValue = (
    args: UseScriptEditorCharactersArgs,
): UseScriptCharactersContextValueResult => {
    const {
        applyDocumentChange,
        getEditorValue,
        editorOverrideValue,
        confirmedCharacterRecords,
        confirmedGroupRecords,
        normalizedConfirmedCharacterRecords,
        normalizedSpeakingEntityRecords,
        pendingCharacterKeys,
        deletingCharacterIds,
        renamingCharacterIds,
        renamingCharacterKeys,
        colorUpdatingCharacterIds,
        genderUpdatingCharacterIds,
        creatingGroupKeys,
        deletingGroupIds,
        renamingGroupIds,
        colorUpdatingGroupIds,
        membershipUpdatingGroupIds,
        characterGenderOptions,
        isCharactersLoading,
        handleEditorValueChange,
        normalizeCharacterNameForInlineInput,
        handleConfirmCharacter,
        handleDeleteCharacter,
        handleRenameCharacterPreview,
        handleRenameCharacter,
        handleSetCharacterColor,
        handleSetCharacterGender,
        handleSetCharacterOutline,
        handleUpsertCharacterGender,
        handleCreateGroup,
        handleDeleteGroup,
        handleRenameGroup,
        handleSetGroupColor,
        handleReplaceGroupMembers,
    } = useScriptEditorCharacters(args);

    const handleResolvedEditorValueChange = useCallback((
        value: Parameters<typeof handleEditorValueChange>[0],
        meta?: Parameters<typeof handleEditorValueChange>[1],
    ) => {
        handleEditorValueChange(value, meta);
    }, [handleEditorValueChange]);

    const contextValue: ScriptCharactersContextValue = useMemo(() => ({
        getEditorValue,
        editorOverrideValue,
        normalizedConfirmedCharacterRecords,
        normalizedSpeakingEntityRecords,
        handleEditorValueChange,
        confirmedCharacterRecords,
        confirmedGroupRecords,
        pendingCharacterKeys,
        deletingCharacterIds,
        renamingCharacterIds,
        renamingCharacterKeys,
        colorUpdatingCharacterIds,
        genderUpdatingCharacterIds,
        creatingGroupKeys,
        deletingGroupIds,
        renamingGroupIds,
        colorUpdatingGroupIds,
        membershipUpdatingGroupIds,
        characterGenderOptions,
        isCharactersLoading,
        normalizeCharacterNameForInlineInput,
        handleConfirmCharacter,
        handleDeleteCharacter,
        handleRenameCharacterPreview,
        handleRenameCharacter,
        handleSetCharacterColor,
        handleSetCharacterGender,
        handleSetCharacterOutline,
        handleUpsertCharacterGender,
        handleCreateGroup,
        handleDeleteGroup,
        handleRenameGroup,
        handleSetGroupColor,
        handleReplaceGroupMembers,
    }), [
        characterGenderOptions,
        colorUpdatingCharacterIds,
        confirmedCharacterRecords,
        confirmedGroupRecords,
        creatingGroupKeys,
        deletingGroupIds,
        deletingCharacterIds,
        editorOverrideValue,
        getEditorValue,
        genderUpdatingCharacterIds,
        handleConfirmCharacter,
        handleCreateGroup,
        handleDeleteCharacter,
        handleDeleteGroup,
        handleEditorValueChange,
        handleRenameCharacter,
        handleRenameCharacterPreview,
        handleRenameGroup,
        handleSetCharacterColor,
        handleSetCharacterGender,
        handleSetCharacterOutline,
        handleSetGroupColor,
        handleReplaceGroupMembers,
        handleUpsertCharacterGender,
        isCharactersLoading,
        normalizeCharacterNameForInlineInput,
        normalizedConfirmedCharacterRecords,
        normalizedSpeakingEntityRecords,
        pendingCharacterKeys,
        renamingCharacterIds,
        renamingCharacterKeys,
        renamingGroupIds,
        colorUpdatingGroupIds,
        membershipUpdatingGroupIds,
    ]);

    return {
        applyDocumentChange,
        getEditorValue,
        editorOverrideValue,
        normalizedConfirmedCharacterRecords,
        normalizedSpeakingEntityRecords,
        handleResolvedEditorValueChange,
        contextValue,
    };
};
