// This file is auto-generated by scripts/compile-migrations.mjs. Do not edit by hand.

export const compiledMigrations = [
    {
        "id": "0000_initial",
        "sql": "CREATE TABLE IF NOT EXISTS \"scripts\" (\n    \"id\" text PRIMARY KEY,\n    \"title\" text NOT NULL,\n    \"created_at\" bigint NOT NULL,\n    \"updated_at\" bigint NOT NULL,\n    \"active_block_id\" text\n);\n\nCREATE TABLE IF NOT EXISTS \"script_latest\" (\n    \"script_id\" text PRIMARY KEY REFERENCES \"scripts\"(\"id\") ON DELETE CASCADE,\n    \"content_json\" text NOT NULL,\n    \"updated_at\" bigint NOT NULL,\n    \"schema_version\" integer NOT NULL DEFAULT 1\n);\n\nCREATE TABLE IF NOT EXISTS \"script_versions\" (\n    \"id\" text PRIMARY KEY,\n    \"script_id\" text NOT NULL REFERENCES \"scripts\"(\"id\") ON DELETE CASCADE,\n    \"message\" text,\n    \"content_json\" text NOT NULL,\n    \"created_at\" bigint NOT NULL,\n    \"schema_version\" integer NOT NULL DEFAULT 1\n);\n\nCREATE INDEX IF NOT EXISTS \"script_versions_script_id_created_at_idx\"\n    ON \"script_versions\" (\"script_id\", \"created_at\");\n\nCREATE TABLE IF NOT EXISTS \"sync_outbox\" (\n    \"id\" text PRIMARY KEY,\n    \"script_id\" text,\n    \"op_type\" text,\n    \"payload_json\" text,\n    \"created_at\" bigint,\n    \"status\" text NOT NULL DEFAULT 'pending'\n);\n"
    }
] as const;
