import stylisticPlugin from '@stylistic/stylelint-plugin';
import stylelintConfigCleanOrder, {propertyGroups} from 'stylelint-config-clean-order';
import stylelintOrder from 'stylelint-order';

const propertiesOrder = propertyGroups.map(properties => ({
    noEmptyLineBetween: true,
    emptyLineBefore: 'never',
    properties,
}));

const index = {
    plugins: [stylelintOrder, stylisticPlugin],
    ignoreFiles: ['**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx', '**/node_modules/**'],
    rules: {
        ...stylelintConfigCleanOrder.rules,
        // recommended
        'annotation-no-unknown': true,
        'block-no-empty': true,
        'color-no-invalid-hex': true,
        'comment-no-empty': true,
        'custom-property-no-missing-var-function': true,
        'declaration-block-no-duplicate-custom-properties': true,
        'declaration-block-no-duplicate-properties': [
            true,
            {
                ignore: ['consecutive-duplicates-with-different-syntaxes'],
            },
        ],
        'declaration-block-no-shorthand-property-overrides': true,
        'font-family-no-duplicate-names': true,
        'font-family-no-missing-generic-family-keyword': true,
        'function-calc-no-unspaced-operator': true,
        'function-linear-gradient-no-nonstandard-direction': true,
        'function-no-unknown': true,
        'keyframe-block-no-duplicate-selectors': true,
        'keyframe-declaration-no-important': true,
        'media-query-no-invalid': true,
        'named-grid-areas-no-invalid': true,
        'no-duplicate-at-import-rules': true,
        'no-duplicate-selectors': true,
        'no-empty-source': true,
        'no-invalid-double-slash-comments': true,
        'no-invalid-position-at-import-rule': true,
        'no-irregular-whitespace': true,
        'selector-anb-no-unmatchable': true,
        'selector-pseudo-element-no-unknown': true,
        'selector-type-no-unknown': [
            true,
            {
                ignore: ['custom-elements'],
            },
        ],
        'string-no-newline': true,
        'unit-no-unknown': true,
        // custom
        'at-rule-empty-line-before': [
            'always',
            {
                except: ['blockless-after-same-name-blockless'],
                ignore: ['after-comment'],
                ignoreAtRules: ['font-face', 'mixin', 'include', 'extend', 'custom-media'],
            },
        ],
        '@stylistic/at-rule-name-case': 'lower',
        '@stylistic/at-rule-name-space-after': 'always',
        'at-rule-no-vendor-prefix': true,
        'at-rule-no-unknown': [
            true,
            {
                ignoreAtRules: ['import-normalize', 'mixin', 'include', 'extend', 'custom-media'],
            },
        ],
        '@stylistic/at-rule-semicolon-newline-after': 'always',
        '@stylistic/at-rule-semicolon-space-before': 'never',
        '@stylistic/block-closing-brace-empty-line-before': 'never',
        '@stylistic/block-closing-brace-newline-after': 'always',
        '@stylistic/block-closing-brace-newline-before': 'always',
        '@stylistic/block-opening-brace-newline-after': 'always',
        '@stylistic/block-opening-brace-newline-before': 'never-single-line',
        '@stylistic/block-opening-brace-space-before': 'always',
        'declaration-property-value-no-unknown': true,
        '@stylistic/color-hex-case': 'lower',
        'color-hex-length': 'short',
        'color-named': 'never',
        'comment-whitespace-inside': 'always',
        'custom-property-empty-line-before': 'never',
        '@stylistic/declaration-bang-space-after': 'never',
        '@stylistic/declaration-bang-space-before': 'always',
        'declaration-block-no-redundant-longhand-properties': true,
        '@stylistic/declaration-block-semicolon-newline-after': 'always',
        '@stylistic/declaration-block-semicolon-newline-before': 'never-multi-line',
        '@stylistic/declaration-block-semicolon-space-after': 'always-single-line',
        '@stylistic/declaration-block-semicolon-space-before': 'never',
        '@stylistic/declaration-block-trailing-semicolon': 'always',
        'declaration-block-single-line-max-declarations': 1,
        '@stylistic/declaration-colon-space-after': 'always',
        '@stylistic/declaration-colon-space-before': 'never',
        '@stylistic/function-comma-newline-after': 'never-multi-line',
        '@stylistic/function-comma-newline-before': 'never-multi-line',
        '@stylistic/function-comma-space-after': 'always',
        '@stylistic/function-comma-space-before': 'never',
        '@stylistic/function-max-empty-lines': 0,
        'function-name-case': 'lower',
        '@stylistic/function-parentheses-newline-inside': 'never-multi-line',
        '@stylistic/function-parentheses-space-inside': 'never',
        'function-url-no-scheme-relative': true,
        'function-url-quotes': 'always',
        '@stylistic/function-whitespace-after': 'always',
        '@stylistic/indentation': 4,
        'length-zero-no-unit': [
            true,
            {
                ignore: ['custom-properties'],
            },
        ],
        '@stylistic/max-empty-lines': 1,
        'max-nesting-depth': 4,
        '@stylistic/media-feature-colon-space-after': 'always',
        '@stylistic/media-feature-colon-space-before': 'never',
        '@stylistic/media-feature-name-case': 'lower',
        'media-feature-name-no-unknown': [
            true,
            {
                ignoreMediaFeatureNames: ['prefers-reduced-motion'],
            },
        ],
        'media-feature-name-no-vendor-prefix': true,
        '@stylistic/media-feature-parentheses-space-inside': 'never',
        '@stylistic/media-feature-range-operator-space-after': 'always',
        '@stylistic/media-feature-range-operator-space-before': 'always',
        '@stylistic/media-query-list-comma-newline-after': 'always',
        '@stylistic/media-query-list-comma-newline-before': 'never-multi-line',
        '@stylistic/media-query-list-comma-space-after': 'always-single-line',
        '@stylistic/media-query-list-comma-space-before': 'never',
        'no-descending-specificity': null,
        'no-unknown-animations': [
            true,
            {
                severity: 'warning',
            },
        ],
        'order/properties-order': [
            propertiesOrder,
            {
                severity: 'warning',
                unspecified: 'bottomAlphabetical',
            },
        ],
        'order/order': [
            'custom-properties',
            'declarations',
            {
                type: 'rule',
                selector: '^&:[\\w-]+',
            },
            {
                type: 'rule',
                selector: '^&::[\\w-]+',
            },
            {
                type: 'rule',
                selector: '^&.-[\\w-]+',
            },
            {
                type: 'rule',
                selector: '^&\\[',
            },
            {
                type: 'rule',
                selector: '^&__[\\w-]+',
            },
            {
                type: 'rule',
                selector: '^[>|+|~] .[\\w-]+',
            },
            {
                type: 'rule',
                selector: '^.[\\w-]+ &',
            },
            'rules',
            'at-rules',
        ],
        '@stylistic/number-leading-zero': 'never',
        '@stylistic/number-no-trailing-zeros': true,
        '@stylistic/property-case': 'lower',
        'property-no-vendor-prefix': true,
        'property-no-unknown': [
            true,
            {
                ignoreProperties: ['composes', 'appearance'],
            },
        ],
        // '@stylistic/rule-empty-line-before': 'always',
        '@stylistic/selector-attribute-brackets-space-inside': 'never',
        '@stylistic/selector-attribute-operator-space-after': 'always',
        '@stylistic/selector-attribute-operator-space-before': 'always',
        'selector-attribute-quotes': 'always',
        '@stylistic/selector-combinator-space-after': 'always',
        '@stylistic/selector-combinator-space-before': 'always',
        '@stylistic/selector-list-comma-newline-after': 'always',
        '@stylistic/selector-list-comma-newline-before': 'never-multi-line',
        '@stylistic/selector-list-comma-space-after': 'always-single-line',
        '@stylistic/selector-list-comma-space-before': 'never',
        'selector-max-class': 3,
        'selector-max-compound-selectors': 5,
        '@stylistic/selector-max-empty-lines': 0,
        'selector-max-id': 1,
        'selector-max-type': 1,
        'selector-no-qualifying-type': [
            true,
            {
                ignore: ['attribute'],
            },
        ],
        'selector-no-vendor-prefix': true,
        '@stylistic/selector-pseudo-class-case': 'lower',
        'selector-pseudo-class-no-unknown': [
            true,
            {
                ignorePseudoClasses: ['global', 'local'],
            },
        ],
        '@stylistic/selector-pseudo-class-parentheses-space-inside': 'never',
        '@stylistic/selector-pseudo-element-case': 'lower',
        'selector-pseudo-element-colon-notation': 'double',
        'selector-type-case': 'lower',
        'shorthand-property-no-redundant-values': true,
        '@stylistic/string-quotes': 'single',
        '@stylistic/unit-case': 'lower',
        'value-keyword-case': 'lower',
        '@stylistic/value-list-comma-newline-after': 'never-multi-line',
        '@stylistic/value-list-comma-newline-before': 'never-multi-line',
        '@stylistic/value-list-comma-space-after': 'always',
        '@stylistic/value-list-comma-space-before': 'never',
        '@stylistic/value-list-max-empty-lines': 0,
        'value-no-vendor-prefix': true,
    },
};

export default index;
