import {
    ELEMENT_ACTION,
    ELEMENT_CENTERED,
    ELEMENT_CHARACTER,
    ELEMENT_DIALOGUE,
    ELEMENT_DUAL_DIALOGUE,
    ELEMENT_DUAL_DIALOGUE_CHARACTER,
    ELEMENT_LYRICS,
    ELEMENT_PARENTHETICAL,
    ELEMENT_SCENE_HEADING,
    ELEMENT_TRANSITION,
} from '../fountain';
import {CHARACTER_COLOR_SATURATION_DEFAULT} from './options';
import type {EditorSettings} from './types';

export const DEFAULT_EDITOR_SETTINGS: EditorSettings = {
    page: {
        widthPx: 794,
        heightPx: 1123,
        marginTopPx: 96,
        marginRightPx: 96,
        marginBottomPx: 96,
        marginLeftPx: 144,
        pageGapPx: 32,
        pageBreakBackground: 'var(--color-surface)',
        contentMarginTopPx: 0,
        contentMarginBottomPx: 0,
    },
    typography: {
        fontSizePx: 16,
        lineHeight: 1.0,
    },
    visual: {
        characterColorSaturation: CHARACTER_COLOR_SATURATION_DEFAULT,
    },
    blocks: {
        [ELEMENT_ACTION]: {
            spacingBeforeEm: 1.0,
            lineHeight: 1.0,
            shortcut: '2',
            nextElement: ELEMENT_ACTION,
            textAlign: 'left',
            casing: 'normal',
            isBold: false,
            isItalic: false,
            isUnderline: false,
        },
        [ELEMENT_SCENE_HEADING]: {
            spacingBeforeEm: 2.0,
            lineHeight: 1.0,
            shortcut: '1',
            nextElement: ELEMENT_ACTION,
            textAlign: 'left',
            casing: 'uppercase',
            isBold: true,
            isItalic: false,
            isUnderline: false,
        },
        [ELEMENT_CHARACTER]: {
            spacingBeforeEm: 1.0,
            lineHeight: 1.0,
            indentLeftChars: 20,
            indentRightChars: 3,
            shortcut: '3',
            nextElement: ELEMENT_DIALOGUE,
            textAlign: 'left',
            casing: 'uppercase',
            isBold: true,
            isItalic: false,
            isUnderline: false,
        },
        [ELEMENT_DUAL_DIALOGUE_CHARACTER]: {
            spacingBeforeEm: 1.0,
            lineHeight: 1.0,
            indentLeftChars: 20,
            indentRightChars: 3,
            shortcut: '9',
            nextElement: ELEMENT_DIALOGUE,
            textAlign: 'left',
            casing: 'uppercase',
            isBold: true,
            isItalic: false,
            isUnderline: false,
        },
        [ELEMENT_PARENTHETICAL]: {
            spacingBeforeEm: 0,
            lineHeight: 1.0,
            indentLeftChars: 16,
            indentRightChars: 21,
            shortcut: '4',
            nextElement: ELEMENT_CHARACTER,
            textAlign: 'left',
            casing: 'normal',
            isBold: false,
            isItalic: true,
            isUnderline: false,
        },
        [ELEMENT_DIALOGUE]: {
            spacingBeforeEm: 0,
            lineHeight: 1.0,
            indentLeftChars: 10,
            indentRightChars: 3,
            shortcut: '5',
            nextElement: ELEMENT_CHARACTER,
            textAlign: 'left',
            casing: 'normal',
            isBold: false,
            isItalic: false,
            isUnderline: false,
        },
        [ELEMENT_DUAL_DIALOGUE]: {
            spacingBeforeEm: 0,
            lineHeight: 1.0,
            indentLeftChars: 10,
            indentRightChars: 3,
            shortcut: '5',
            nextElement: ELEMENT_CHARACTER,
            textAlign: 'left',
            casing: 'normal',
            isBold: false,
            isItalic: false,
            isUnderline: false,
        },
        [ELEMENT_TRANSITION]: {
            spacingBeforeEm: 1.0,
            lineHeight: 1.0,
            indentRightChars: 5,
            shortcut: '6',
            nextElement: ELEMENT_SCENE_HEADING,
            textAlign: 'right',
            casing: 'uppercase',
            isBold: true,
            isItalic: false,
            isUnderline: false,
        },
        [ELEMENT_LYRICS]: {
            spacingBeforeEm: 0,
            lineHeight: 1.0,
            indentLeftChars: 10,
            indentRightChars: 10,
            shortcut: '7',
            nextElement: ELEMENT_LYRICS,
            textAlign: 'left',
            casing: 'normal',
            isBold: false,
            isItalic: true,
            isUnderline: false,
        },
        [ELEMENT_CENTERED]: {
            shortcut: '8',
            nextElement: ELEMENT_CENTERED,
            textAlign: 'center',
            casing: 'normal',
            isBold: false,
            isItalic: true,
            isUnderline: false,
        },
    },
};
