import {
    ELEMENT_ACT,
    ELEMENT_ACTION,
    ELEMENT_CHARACTER,
    ELEMENT_DIALOGUE,
    ELEMENT_DUAL_DIALOGUE,
    ELEMENT_DUAL_DIALOGUE_CHARACTER,
    ELEMENT_LYRICS,
    ELEMENT_NOTE,
    ELEMENT_PARENTHETICAL,
    ELEMENT_SCENE_HEADING,
    ELEMENT_SECTION,
    ELEMENT_TRANSITION,
} from '../fountain';
import {CHARACTER_COLOR_SATURATION_DEFAULT} from './options';
import type {EditorSettings} from './types';

export const DEFAULT_EDITOR_SETTINGS: EditorSettings = {
    page: {
        widthPx: 794,
        heightPx: 1123,
        marginTopPx: 96,
        marginRightPx: 96,
        marginBottomPx: 96,
        marginLeftPx: 144,
        pageGapPx: 32,
        pageBreakBackground: 'var(--color-surface)',
        contentMarginTopPx: 0,
        contentMarginBottomPx: 0,
    },
    typography: {
        fontSizePx: 16,
        lineHeight: 1.2,
    },
    visual: {
        characterColorSaturation: CHARACTER_COLOR_SATURATION_DEFAULT,
    },
    structure: {
        actPrefix: 'ACT:',
        actDisplay: {
            linesBefore: 1,
            linesAfter: 1,
        },
        musicPrefixes: {
            song: {
                start: 'SONG:',
                end: 'SONG END:',
            },
            reprise: {
                start: 'REPRISE:',
                end: 'REPRISE END:',
            },
            underscore: {
                start: 'UNDERSCORE:',
                end: 'UNDERSCORE END:',
            },
        },
    },
    blocks: {
        [ELEMENT_ACTION]: {
            spacingBeforeEm: 1.0,
            lineHeight: 1.2,
            shortcut: '2',
            nextElement: ELEMENT_ACTION,
            textAlign: 'left',
            casing: 'normal',
            isBold: false,
            isItalic: false,
            isUnderline: false,
        },
        [ELEMENT_ACT]: {
            spacingBeforeEm: 1.0,
            lineHeight: 1.2,
            nextElement: ELEMENT_SCENE_HEADING,
            textAlign: 'left',
            casing: 'uppercase',
            isBold: true,
            isItalic: false,
            isUnderline: true,
        },
        [ELEMENT_SECTION]: {
            spacingBeforeEm: 1.0,
            lineHeight: 1.2,
            nextElement: ELEMENT_ACTION,
            textAlign: 'left',
            casing: 'uppercase',
            isBold: true,
            isItalic: false,
            isUnderline: false,
        },
        [ELEMENT_SCENE_HEADING]: {
            spacingBeforeEm: 2.0,
            lineHeight: 1.2,
            shortcut: '1',
            nextElement: ELEMENT_ACTION,
            textAlign: 'left',
            casing: 'uppercase',
            isBold: true,
            isItalic: false,
            isUnderline: false,
        },
        [ELEMENT_CHARACTER]: {
            spacingBeforeEm: 1.0,
            lineHeight: 1.2,
            indentLeftChars: 20,
            indentRightChars: 3,
            shortcut: '3',
            nextElement: ELEMENT_DIALOGUE,
            textAlign: 'left',
            casing: 'uppercase',
            isBold: true,
            isItalic: false,
            isUnderline: false,
        },
        [ELEMENT_DUAL_DIALOGUE_CHARACTER]: {
            spacingBeforeEm: 1.0,
            lineHeight: 1.2,
            indentLeftChars: 20,
            indentRightChars: 3,
            shortcut: '9',
            nextElement: ELEMENT_DIALOGUE,
            textAlign: 'left',
            casing: 'uppercase',
            isBold: true,
            isItalic: false,
            isUnderline: false,
        },
        [ELEMENT_PARENTHETICAL]: {
            spacingBeforeEm: 0,
            lineHeight: 1.2,
            indentLeftChars: 16,
            indentRightChars: 21,
            shortcut: '4',
            nextElement: ELEMENT_CHARACTER,
            textAlign: 'left',
            casing: 'normal',
            isBold: false,
            isItalic: true,
            isUnderline: false,
        },
        [ELEMENT_DIALOGUE]: {
            spacingBeforeEm: 0,
            lineHeight: 1.2,
            indentLeftChars: 10,
            indentRightChars: 3,
            shortcut: '5',
            nextElement: ELEMENT_CHARACTER,
            textAlign: 'left',
            casing: 'normal',
            isBold: false,
            isItalic: false,
            isUnderline: false,
        },
        [ELEMENT_DUAL_DIALOGUE]: {
            spacingBeforeEm: 0,
            lineHeight: 1.2,
            indentLeftChars: 10,
            indentRightChars: 3,
            shortcut: '5',
            nextElement: ELEMENT_CHARACTER,
            textAlign: 'left',
            casing: 'normal',
            isBold: false,
            isItalic: false,
            isUnderline: false,
        },
        [ELEMENT_TRANSITION]: {
            spacingBeforeEm: 1.0,
            lineHeight: 1.2,
            indentRightChars: 5,
            shortcut: '6',
            nextElement: ELEMENT_SCENE_HEADING,
            textAlign: 'right',
            casing: 'uppercase',
            isBold: true,
            isItalic: false,
            isUnderline: false,
        },
        [ELEMENT_LYRICS]: {
            spacingBeforeEm: 0,
            lineHeight: 1.2,
            indentLeftChars: 10,
            indentRightChars: 10,
            shortcut: '7',
            nextElement: ELEMENT_LYRICS,
            textAlign: 'left',
            casing: 'normal',
            isBold: false,
            isItalic: true,
            isUnderline: false,
        },
        [ELEMENT_NOTE]: {
            spacingBeforeEm: 1.0,
            lineHeight: 1.2,
            shortcut: '0',
            nextElement: ELEMENT_ACTION,
            textAlign: 'left',
            casing: 'normal',
            isBold: false,
            isItalic: false,
            isUnderline: false,
        },
    },
};
