version: '3.9'

services:
  caddy:
    image: caddy:2-alpine
    container_name: stagistic-caddy
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./infra/proxy/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./infra/certs:/etc/caddy/certs:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - default
    depends_on:
      - web
      - api

volumes:
  caddy_data:
  caddy_config:
